### PR TITLE
feat: git tag prefix

### PR DESCRIPTION
**Pull request by lourot**

### CODE REVIEW

**Comment by brillout** [comment]
How about `vike-react@1.2.3` instead of `vike-react-v1.2.3`? That's what Vite does: https://github.com/vitejs/vite/releases.

**Comment by lourot** [comment]
Good point and actually the CLI parser needs to be fixed more, because I discovered that some places in the code assume we support some `--force` and `--dev` flags and they are (already before this PR) broken. I'll rework this PR

**Comment by lourot** [comment]
fixed :)

**Comment by brillout** [comment]
Released as `0.1.11`.

**Pull request merged**
